<?php

function discovery_help($path, $arg) {
	switch ($path) {
		case "admim/help#mymod":
			return '<p>' . t("Display a Multi-Tabbed Search Box on the Frontpage.") . '</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 */
function discovery_menu() {
	// TODO - expose some pages
	// It IS possible to leverage the TRLN WebService API
	return array();
}

function discovery_theme() {
	return array(
		'discovery_searchbox' => array(
			'variables'	=> array('tabs' => NULL),
			'template' => 'discovery-searchbox',
		),
		'discovery_searchbox_tab_all' => array(
			'variables'	=> array('config' => NULL),
			'file' => 'discovery.searchbox.inc',
			'template' => 'discovery-searchbox-tab-all',
		),
		'discovery_searchbox_tab_catalog' => array(
			'variables'	=> array('config' => NULL),
			'file' => 'discovery.searchbox.inc',
			'template' => 'discovery-searchbox-tab-catalog',
		),
		'discovery_searchbox_tab_ejournals' => array(
			'variables'	=> array('config' => NULL),
			'file' => 'discovery.searchbox.inc',
			'template' => 'discovery-searchbox-tab-ejournals',
		),
		'discovery_searchbox_tab_databases' => array(
			'variables'	=> array('config' => NULL),
			'file' => 'discovery.searchbox.inc',
			'template' => 'discovery-searchbox-tab-databases',
		),
	);
}

function discovery_library() {
	$libraries['lib-searchbox'] = array(
		'title' => 'Discovery Widget Library',
		'version' => '1.0.1',
		'js' => array(
			drupal_get_path('module', 'discovery') . '/js/discovery.js' => array(),
		),
		'css' => array(
			drupal_get_path('module', 'discovery') . '/css/discovery.css' => array(
				'type' => 'file',
				'media' => 'all',
				'group' => CSS_DEFAULT,
				'weight' => 6,
			),
		),
	);
	return $libraries;
}
function discovery_block_info() {
	$blocks['searchbox'] = array(
		'info'	=> t('Discovery Multi-Tab Search Box'),
		'cache'	=> DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}

function discovery_block_view($delta = '') {
	$fn_name = 'discovery_show_' . $delta;
	if (function_exists($fn_name)) {
		return call_user_func($fn_name);
	}
	return t('No content to display');
}

function theme_discovery_searchbox($variables) {
	//dpm($variables['tabs']);
	return '<div>' . t('This is what it looks like from the upper deck') . '</div>';
}

function discovery_show_searchbox() {
	$block['subject'] = 'Search Resources';
	
	// If no theme has defined a custom template for this
	// for instance, block--discovery--searchbox.tpl.php
	// then, the above 'theme_searchbox' function will be invoked.
	$tabs = array();
	$tabs[] = array(
		'label' => 'ALL',
		'id' => 'allTab',
		'title' => 'New default search - search articles, books, journals &#38; more',
		'content' => theme('discovery_searchbox_tab_all'),
	);
	$tabs[] = array(
		'label' => 'Catalog',
		'id' => 'catalogTab',
		'content' => theme('discovery_searchbox_tab_catalog'),
	);
	$tabs[] = array(
		'label' => 'eJournal Titles',
		'id' => 'ejournalsTab',
		'content' => theme('discovery_searchbox_tab_ejournals'),
	);
	$tabs[] = array(
		'label' => 'Databases',
		'id' => 'databasesTab',
		'content' => theme('discovery_searchbox_tab_databases'),
	);
	
	//dpm($all_tab);
	$block['content'] = theme('discovery_searchbox', array('tabs' => $tabs));
	watchdog('discovery_show_searchbox', print_r($block, TRUE));
	return $block;
}

/**
 * Implementation of hook_preprocess_block()
 *
 * Please note that, as an alternative, create a template file named
 * 'preprocess-block.inc', residing in /sites/all/themes/dukelib/preprocess
 */
function discovery_preprocess_block(&$vars) {
	if ($vars['block']->delta == 'searchbox') {
		drupal_add_js('http://library.duke.edu/javascript/blue-note/home-search-box.js', 'external');
		drupal_add_js('http://library.duke.edu/javascript/blue-note/home-search-box-extras.js', 'external');
		drupal_add_js('http://autosuggest.trln.org/plugins/jquery.trln.autocomplete.js', 'external');
		drupal_add_js('http://autosuggest.trln.org/plugins/jquery.trln.autosuggest.js', 'external');
		drupal_add_css('http://autosuggest.trln.org/plugins/DUKE_autosuggest.css', 'external');
		drupal_add_library('discovery', 'lib-searchbox', FALSE);
	}
}
