<?php

/**
 * Implementation of hook_help()
 */
function dukelib_ui_help($path, $arg) {
	switch ($path) {
		case 'admin/help#dukelib_ui':
			return '<p>' . t('Provides common UI widgets for Duke Library Websites.') . '</p>';
			break;
	}
}

/**
 * Implementation of hook_menu().
 */
function dukelib_ui_menu() {
	return array();
}

/**
 * Implementation of hook_theme().
 */
function dukelib_ui_theme() {
	return array(
		'ask_us_button_description' => array(
			'variables' => array(),
		),
		'social_links' => array(
			'variables' => array(),
			'template' => 'dukelib_ui_social_links',
			'file' => 'dukelib_ui.social_links.inc',
		),
		'cc_license' => array(
			'variables' => array(),
			'template' => 'dukelib_ui_cc_license',
			'file' => 'dukelib_ui.cc_license.inc',
		),
	);
}

/**
 * Implementation of hook_block_info().
 */
function dukelib_ui_block_info() {
	$blocks['ask_us_now'] = array(
		'info' => t('"Ask Us Now" button'),
		'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['social_links'] = array(
		'info' => t('Footer Social Links'),
		'description' => '<p>' . t('Social link buttons (Twitter, Facebook, etc) intended for display on the footer.') . '</p>',
		'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['cc_license'] = array(
		'info' => t('Creative Commons License Text'),
		'cache' => DRUPAL_NO_CACHE,
	);
	return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function dukelib_ui_block_view($delta = '') {
	global $base_url;
	if ($delta == 'ask_us_now') {
		$button_file = variable_get('ask_us_button', 'large') == 'large' ? 'ask-us.jpg' : 'ask_interior.gif';
		$block['title'] = '';
		$block['subject'] = '';
		$block['content'] = '<a href="#">'
			. '<img src="' . $base_url . '/' . drupal_get_path('module', 'dukelib_ui')
			. '/images/' . $button_file
			. '" />';
		return $block;
	}
	if ($delta == 'social_links') {
		$block['title'] = '';
		$block['subject'] = '';
		$block['content'] = theme('social_links', array());
		return $block;
	}
	if ($delta == 'cc_license') {
		$block['title'] = '';
		$block['subject'] = '';
		$block['content'] = theme('cc_license', array());
		return $block;
	}
	return t('Content coming soon.');
}

/**
 * Implementation of hook_block_configure().
 */
function dukelib_ui_block_configure($delta = '') {
	$form = array();
	if ($delta == 'ask_us_now') {
		$description = theme('ask_us_button_description', array());
		$form['ask_us_button'] = array(
			'#type' => 'select',
			'#title' => t('Button Type'),
			'#options' => array(
				'large' => t('Large Button'),
				'small' => t('Small Button'),
			),
			'#default_value' => variable_get('ask_us_button', 'large'),
			'#description' => $description,
		);
	}
	return $form;
}

/**
 * Implements hook_block_save()
 * 
 * For the 'ask_us_now' delta, it stores the button selection.
 */
function dukelib_ui_block_save($delta = '', $edit = array()) {
	if ($delta == 'ask_us_now') {
		variable_set('ask_us_button', $edit['ask_us_button']);
	}
	return;
}

/**
 * ask_us_button_description
 *
 * @themable
 */
function theme_ask_us_button_description($vars) {
	global $base_url;
	$h = '<div style="margin-bottom: 1em;"><strong>' . t('Select from one of these available buttons to display:') . '</strong></div>'
		. '<div>'
		. '<em>Large:</em><br />'
		. '<img src="' . $base_url . '/' . drupal_get_path('module', 'dukelib_ui') . '/images/ask-us.jpg' . '" /><br />'
		. '<em>Small:</em></br />'
		. '<img src="' . $base_url . '/' . drupal_get_path('module', 'dukelib_ui') . '/images/ask_interior.gif' . '" />'
		. '</div>';

	return $h;
}
